; PlatformIO Project Configuration File

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags = -std=gnu++17
build_unflags = -std=gnu++11
lib_ldf_mode = deep

lib_deps =
    waspinator/AccelStepper@^1.64
    https://github.com/sinricpro/esp8266-esp32-sdk.git
    me-no-dev/ESPAsyncWebServer@^1.2.4
    me-no-dev/AsyncTCP@^1.1.1
    bblanchon/ArduinoJson@^7.4.1
    https://github.com/VisTechProjectsOrg/esp32_ota_updater.git

; Uncomment for OTA upload:
; upload_protocol = espota
; upload_port = smartblinds.local
